name: Dependency-Track SBOM

on:
  workflow_dispatch:
  push:
    branches:
      - '1.1'

jobs:
  dependency-track:
    uses: DoubtfulTurnip/.github/.github/workflows/dependency-track-sbom.yml@main
    secrets:
      dependencytrack-api-key: ${{ secrets.DEPENDENCYTRACK_API_KEY }}
